version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - ./provisioning/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NODE_ENV=development
    ports:
      - 80:80
    depends_on:

      - client




  client:
    build: .
    volumes:
      - .:/code
    command: npm run client:watch -- --host 0.0.0.0 --port 8080
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
      - 35729:35729



